import { GithubCommitResponse } from 'src/infrastructure/interfaces/github-commit-response.interface';

export const resultGithubCommitResponse: GithubCommitResponse = {
  sha: 'test',
  node_id: 'test',
  commit: {
    author: {
      name: 'test',
      email: 'test',
      date: 'test',
    },
    committer: {
      name: 'test',
      email: 'test',
      date: 'test',
    },
    message: 'test',
    tree: {
      sha: 'test',
      url: 'test',
    },
    url: 'test',
    comment_count: 0,
    verification: {
      verified: false,
      reason: 'test',
      signature: 'test',
      payload: 'test',
    },
  },
  url: 'test',
  html_url: 'test',
  comments_url: 'test',
  author: {
    login: 'test',
    id: 0,
    node_id: 'test',
    avatar_url: 'test',
    gravatar_id: 'test',
    url: 'test',
    html_url: 'test',
    followers_url: 'test',
    following_url: 'test',
    gists_url: 'test',
    starred_url: 'test',
    subscriptions_url: 'test',
    organizations_url: 'test',
    repos_url: 'test',
    events_url: 'test',
    received_events_url: 'test',
    type: 'test',
    site_admin: false,
  },
  committer: {
    login: 'test',
    id: 0,
    node_id: 'test',
    avatar_url: 'test',
    gravatar_id: 'test',
    url: 'test',
    html_url: 'test',
    followers_url: 'test',
    following_url: 'test',
    gists_url: 'test',
    starred_url: 'test',
    subscriptions_url: 'test',
    organizations_url: 'test',
    repos_url: 'test',
    events_url: 'test',
    received_events_url: 'test',
    type: 'test',
    site_admin: false,
  },
  parents: [
    {
      sha: 'test',
      url: 'test',
      html_url: 'test',
    },
  ],
};
