import { GithubRepositoryResponse } from 'src/infrastructure/interfaces/github-repository-response';

export const resultGithubRepositoryResponse: GithubRepositoryResponse[] = [
  {
    id: 0,
    node_id: 'test',
    name: 'test',
    full_name: 'test',
    private: true,
    owner: {
      login: 'test',
      id: 0,
      node_id: 'test',
      avatar_url: 'test',
      gravatar_id: 'test',
      url: 'test',
      html_url: 'test',
      followers_url: 'test',
      following_url: 'test',
      gists_url: 'test',
      starred_url: 'test',
      subscriptions_url: 'test',
      organizations_url: 'test',
      repos_url: 'test',
      events_url: 'test',
      received_events_url: 'test',
      type: 'test',
      site_admin: false,
    },
    html_url: 'test',
    description: 'test',
    fork: false,
    url: 'test',
    forks_url: 'test',
    keys_url: 'test',
    collaborators_url: 'test',
    teams_url: 'test',
    hooks_url: 'test',
    issue_events_url: 'test',
    events_url: 'test',
    assignees_url: 'test',
    branches_url: 'test',
    tags_url: 'test',
    blobs_url: 'test',
    git_tags_url: 'test',
    git_refs_url: 'test',
    trees_url: 'test',
    statuses_url: 'test',
    languages_url: 'test',
    stargazers_url: 'test',
    contributors_url: 'test',
    subscribers_url: 'test',
    subscription_url: 'test',
    commits_url: 'test',
    git_commits_url: 'test',
    comments_url: 'test',
    issue_comment_url: 'test',
    contents_url: 'test',
    compare_url: 'test',
    merges_url: 'test',
    archive_url: 'test',
    downloads_url: 'test',
    issues_url: 'test',
    pulls_url: 'test',
    milestones_url: 'test',
    notifications_url: 'test',
    labels_url: 'test',
    releases_url: 'test',
    deployments_url: 'test',
    created_at: 'test',
    updated_at: 'test',
    pushed_at: 'test',
    git_url: 'test',
    ssh_url: 'test',
    clone_url: 'test',
    svn_url: 'test',
    homepage: 'test',
    size: 0,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'test',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    forks_count: 0,
    mirror_url: 'test',
    archived: true,
    disabled: true,
    open_issues_count: 0,
    license: 'test',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'test',
  },
];

export const resultGithubRepositoryResponseForked: GithubRepositoryResponse[] = [
  {
    id: 0,
    node_id: 'test',
    name: 'test',
    full_name: 'test',
    private: true,
    owner: {
      login: 'test',
      id: 0,
      node_id: 'test',
      avatar_url: 'test',
      gravatar_id: 'test',
      url: 'test',
      html_url: 'test',
      followers_url: 'test',
      following_url: 'test',
      gists_url: 'test',
      starred_url: 'test',
      subscriptions_url: 'test',
      organizations_url: 'test',
      repos_url: 'test',
      events_url: 'test',
      received_events_url: 'test',
      type: 'test',
      site_admin: false,
    },
    html_url: 'test',
    description: 'test',
    fork: false,
    url: 'test',
    forks_url: 'test',
    keys_url: 'test',
    collaborators_url: 'test',
    teams_url: 'test',
    hooks_url: 'test',
    issue_events_url: 'test',
    events_url: 'test',
    assignees_url: 'test',
    branches_url: 'test',
    tags_url: 'test',
    blobs_url: 'test',
    git_tags_url: 'test',
    git_refs_url: 'test',
    trees_url: 'test',
    statuses_url: 'test',
    languages_url: 'test',
    stargazers_url: 'test',
    contributors_url: 'test',
    subscribers_url: 'test',
    subscription_url: 'test',
    commits_url: 'test',
    git_commits_url: 'test',
    comments_url: 'test',
    issue_comment_url: 'test',
    contents_url: 'test',
    compare_url: 'test',
    merges_url: 'test',
    archive_url: 'test',
    downloads_url: 'test',
    issues_url: 'test',
    pulls_url: 'test',
    milestones_url: 'test',
    notifications_url: 'test',
    labels_url: 'test',
    releases_url: 'test',
    deployments_url: 'test',
    created_at: 'test',
    updated_at: 'test',
    pushed_at: 'test',
    git_url: 'test',
    ssh_url: 'test',
    clone_url: 'test',
    svn_url: 'test',
    homepage: 'test',
    size: 0,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'test',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    forks_count: 0,
    mirror_url: 'test',
    archived: true,
    disabled: true,
    open_issues_count: 0,
    license: 'test',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'test',
  },
  {
    id: 1,
    node_id: 'test 2',
    name: 'test 2',
    full_name: 'test 2',
    private: true,
    owner: {
      login: 'test 2',
      id: 0,
      node_id: 'test 2',
      avatar_url: 'test 2',
      gravatar_id: 'test 2',
      url: 'test 2',
      html_url: 'test 2',
      followers_url: 'test 2',
      following_url: 'test 2',
      gists_url: 'test 2',
      starred_url: 'test 2',
      subscriptions_url: 'test 2',
      organizations_url: 'test 2',
      repos_url: 'test 2',
      events_url: 'test 2',
      received_events_url: 'test 2',
      type: 'test 2',
      site_admin: false,
    },
    html_url: 'test 2',
    description: 'test 2',
    fork: true,
    url: 'test 2',
    forks_url: 'test 2',
    keys_url: 'test 2',
    collaborators_url: 'test 2',
    teams_url: 'test 2',
    hooks_url: 'test 2',
    issue_events_url: 'test 2',
    events_url: 'test 2',
    assignees_url: 'test 2',
    branches_url: 'test 2',
    tags_url: 'test 2',
    blobs_url: 'test 2',
    git_tags_url: 'test 2',
    git_refs_url: 'test 2',
    trees_url: 'test 2',
    statuses_url: 'test 2',
    languages_url: 'test 2',
    stargazers_url: 'test 2',
    contributors_url: 'test 2',
    subscribers_url: 'test 2',
    subscription_url: 'test 2',
    commits_url: 'test 2',
    git_commits_url: 'test 2',
    comments_url: 'test 2',
    issue_comment_url: 'test 2',
    contents_url: 'test 2',
    compare_url: 'test 2',
    merges_url: 'test 2',
    archive_url: 'test 2',
    downloads_url: 'test 2',
    issues_url: 'test 2',
    pulls_url: 'test 2',
    milestones_url: 'test 2',
    notifications_url: 'test 2',
    labels_url: 'test 2',
    releases_url: 'test 2',
    deployments_url: 'test 2',
    created_at: 'test 2',
    updated_at: 'test 2',
    pushed_at: 'test 2',
    git_url: 'test 2',
    ssh_url: 'test 2',
    clone_url: 'test 2',
    svn_url: 'test 2',
    homepage: 'test 2',
    size: 0,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'test 2',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    forks_count: 0,
    mirror_url: 'test 2',
    archived: true,
    disabled: true,
    open_issues_count: 0,
    license: 'test 2',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'test 2',
  },
];
